spring.application.name=eureka-server
server.port=8761

# Eureka Server එක තමන් තුළම ලියාපදිංචි වීම (Self-registration) වැළැක්වීමට
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false